/**
 * @packageDocumentation
 * @module api.functional.memberships
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { MembershipsResponse } from "../../structures/MembershipsResponse";

/**
 * Get all memberships for the authenticated user.
 *
 * Returns loyalty programs grouped by category (airlines, hotels, casinos)
 * with normalized tier levels and unified points values.
 *
 * @tag Memberships
 * @security bearer
 *
 * @controller MembershipsController.getMemberships
 * @path GET /memberships
 * @accessor api.functional.memberships.getMemberships
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMemberships(
  connection: IConnection,
): Promise<getMemberships.Output> {
  return PlainFetcher.fetch(connection, {
    ...getMemberships.METADATA,
    template: getMemberships.METADATA.path,
    path: getMemberships.path(),
  });
}
export namespace getMemberships {
  export type Output = MembershipsResponse;

  export const METADATA = {
    method: "GET",
    path: "/memberships",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/memberships";
}
