/**
 * @packageDocumentation
 * @module api.functional.v2.queries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { PredicateEvaluateResponse } from "../../../structures/PredicateEvaluateResponse";
import type { ProjectionEvaluateResponse } from "../../../structures/ProjectionEvaluateResponse";
import type { QueryEvaluateRequest } from "../../../structures/QueryEvaluateRequest";

/**
 * Evaluate a query against the authenticated user's credentials.
 * This endpoint allows declarative queries to check user claims.
 *
 * @param body The query to evaluate
 * @returns Query evaluation result
 *
 * @controller QueriesController.evaluate
 * @path POST /v2/queries/evaluate
 * @accessor api.functional.v2.queries.evaluate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function evaluate(
  connection: IConnection,
  body: evaluate.Body,
): Promise<evaluate.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...evaluate.METADATA,
      template: evaluate.METADATA.path,
      path: evaluate.path(),
    },
    body,
  );
}
export namespace evaluate {
  export type Body = QueryEvaluateRequest;
  export type Output = PredicateEvaluateResponse | ProjectionEvaluateResponse;

  export const METADATA = {
    method: "POST",
    path: "/v2/queries/evaluate",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/v2/queries/evaluate";
}
