/**
 * @packageDocumentation
 * @module api.functional.v2.developer.organization
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { OrganizationView } from "../../../../structures/OrganizationView";
import type { UpdateOrganizationRequest } from "../../../../structures/UpdateOrganizationRequest";

/**
 * Get the organization for the authenticated developer
 * @controller OrganizationsController.getMyOrganization
 * @path GET /v2/developer/organization
 * @accessor api.functional.v2.developer.organization.getMyOrganization
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMyOrganization(
  connection: IConnection,
): Promise<getMyOrganization.Output> {
  return PlainFetcher.fetch(connection, {
    ...getMyOrganization.METADATA,
    template: getMyOrganization.METADATA.path,
    path: getMyOrganization.path(),
  });
}
export namespace getMyOrganization {
  export type Output = OrganizationView;

  export const METADATA = {
    method: "GET",
    path: "/v2/developer/organization",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/v2/developer/organization";
}

/**
 * Update the organization name (owner only)
 * @controller OrganizationsController.updateMyOrganization
 * @path PUT /v2/developer/organization
 * @accessor api.functional.v2.developer.organization.updateMyOrganization
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateMyOrganization(
  connection: IConnection,
  body: updateMyOrganization.Body,
): Promise<updateMyOrganization.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateMyOrganization.METADATA,
      template: updateMyOrganization.METADATA.path,
      path: updateMyOrganization.path(),
    },
    body,
  );
}
export namespace updateMyOrganization {
  export type Body = UpdateOrganizationRequest;
  export type Output = OrganizationView;

  export const METADATA = {
    method: "PUT",
    path: "/v2/developer/organization",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/v2/developer/organization";
}
