/**
 * @packageDocumentation
 * @module api.functional.v2
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AuthorizationsQuery } from "../../structures/AuthorizationsQuery";
import type { AuthorizationsResponse } from "../../structures/AuthorizationsResponse";

export * as userinfo from "./userinfo/index";
export * as developer from "./developer/index";
export * as presets from "./presets/index";
export * as queries from "./queries/index";

/**
 * @controller StatusController.authorizations
 * @path GET /v2/authorizations
 * @accessor api.functional.v2.authorizations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function authorizations(
  connection: IConnection,
  query: authorizations.Query,
): Promise<authorizations.Output> {
  return PlainFetcher.fetch(connection, {
    ...authorizations.METADATA,
    template: authorizations.METADATA.path,
    path: authorizations.path(query),
  });
}
export namespace authorizations {
  export type Query = AuthorizationsQuery;
  export type Output = AuthorizationsResponse;

  export const METADATA = {
    method: "GET",
    path: "/v2/authorizations",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/v2/authorizations";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
